allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: true
  msw: true
  sharp: true
  unrs-resolver: true

approvedBuilds:
  - '@parcel/watcher@2.5.6'
  - 'msgpackr-extract@3.0.4'
